server:
  host: 0.0.0.0
  port: 8080

tls:
  cert-path: /server.crt
  key-path: /server.key

jwt:
  key-path: /app.rsa
  public-key-path: /app.rsa.pub
  token-duration: 5m
  cookie-duration: 48h
  issuer: psynder
  url: https://localhost:443

postgres:
  username: postgres
  password: 123
  host: localhost
  dbname: postgres