dev-mode: true

server:
  host: 0.0.0.0
  port: 443

tls:
  enable: true
  cert-path: /keys/server.crt
  key-path: /keys/server.key

jwt:
  key-path: /keys/app.rsa
  public-key-path: /keys/app.rsa.pub
  token-duration: 1h
  cookie-duration: 48h
  issuer: psynder
  url: https://localhost:443

postgres:
  username: postgres
  password: 12345678
  host: db
  dbname: postgres