version: '3.1'
services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - "443:443"
      - "444:444"
      - "445:445"
    volumes:
      - ./keys:/keys
      - ./config-docker-shelters.yml:/config-shelters.yml
      - ./config-docker-accounts.yml:/config-accounts.yml
      - ./config-docker-swipes.yml:/config-swipes.yml
  db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
