version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-debug
    depends_on:
      - db
    ports:
      - "443:443"
      - "444:444"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./keys:/keys
      - ./config-docker.yml:/config.yml
      - ./config-docker-shelters.yml:/config_shelters.yml
  db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
